<?php

/**
 * @file
 * Allows to create probabilistic weighted fields.
 */

/**
 * Implements hook_field_info().
 */
function probabilistic_weight_field_info() {

  return array(
    'probabilistic_weight' => array(
      'label' => t('Probabilistic weight'),
      'description' => t('Probabilistic weight'),
      'settings' => array(
        'max_length' => 128,
      ),
      'default_widget' => 'probabilistic_weight_widget_text',
      'default_formatter' => 'probabilistic_weight_formatter_text',
      'property_type' => 'decimal',
    ),
  );

}

/**
 * Implements hook_field_is_empty().
 */
function probabilistic_weight_field_is_empty($item, $field) {

  return empty($item['weight']);

}

/**
 * Implements hook_field_formatter_info().
 */
function probabilistic_weight_field_formatter_info() {

  return array(
    'probabilistic_weight_formatter_text' => array(
      'label' => t('Text'),
      'field types' => array('probabilistic_weight'),
    ),
  );

}

/**
 * Implements hook_field_widget_info().
 */
function probabilistic_weight_field_widget_info() {

  return array(
    'probabilistic_weight_widget_text' => array(
      'label' => t('Text'),
      'field types' => array('probabilistic_weight'),
    ),
    'probabilistic_weight_widget_slider' => array(
      'label' => t('Slider'),
      'field types' => array('probabilistic_weight'),
    ),
  );

}

/**
 * Implements hook_field_widget_form().
 */
function probabilistic_weight_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta = 0) {

  $pb_weight_slider = &drupal_static(__FUNCTION__, FALSE);

  if (!$pb_weight_slider) {
    $pb_weight_slider = TRUE;
    drupal_add_library('system', 'ui.slider');
    drupal_add_js(
      drupal_get_path('module', 'probabilistic_weight') . '/js/probabilistic_weight_slider.js'
    );
    drupal_add_js(
      array(
        'probabilistic_weight' => array(
          'empty_text' => t('Disable'),
          'disabled_text' => t('Disabled'),
        ),
      ),
      'setting'
    );
  }

  if ($field['cardinality'] == 1) {
    $title = $instance['label'];
  }
  else {
    $title = $instance['label'] . ' (' . $delta . ')';
  }

  $desc = filter_xss_admin($instance['description']);

  $classes = array('prob_weight_field');

  if ($instance['widget']['type'] == 'probabilistic_weight_widget_slider') {
    $classes[] = 'prob_weight_slider';
  }
  if ($instance['required']) {
    $classes[] = 'prob_weight_required';
  }

  $element['weight'] = array(
    '#title' => check_plain($title),
    '#type' => 'textfield',
    '#default_value' => isset($items[$delta]['weight']) ? $items[$delta]['weight'] : '',
    '#attributes' => array('class' => $classes),
    '#required' => $instance['required'],
    '#description' => $desc ? $desc : t('It must be a decimal value greather or equal than 0 and lower or equal than 1.'),
    '#element_validate' => array('probabilistic_weight_validation'),
  );

  return $element;

}

/**
 * Validation for field 'weight' in probabilistic_weight_field_widget_form.
 *
 * @param array $element
 *   Field definition for 'weight'.
 * @param array $form_state
 *   Full form values.
 */
function probabilistic_weight_validation($element, &$form_state) {

  if (!$element['#required']) {
    return;
  }

  $value = $element['#value'];

  if (!is_numeric($value)) {
    form_set_error(
      $element['#parents'][0],
      t(
        '%field must be numeric.',
        array(
          '%field' => $element['#title'],
        )
      )
    );
  }
  elseif ($value < 0) {
    form_set_error(
      $element['#parents'][0],
      t(
        '%field must be greater or equal than 0.',
        array(
          '%field' => $element['#title'],
        )
      )
    );
  }
  elseif ($value > 1) {
    form_set_error(
      $element['#parents'][0],
      t(
        '%field must be lower or equal than 1.',
        array(
          '%field' => $element['#title'],
        )
      )
    );
  }

}

/**
 * Implements hook_field_formatter_view().
 */
function probabilistic_weight_field_formatter_view($object_type, $object, $field, $instance, $langcode, $items, $display) {

  if ($display['type'] == 'probabilistic_weight_formatter_text') {
    $ret = array();
    if (($items) && (count($items) > 0)) {
      foreach ($items as $item) {
        $ret[] = array(
          '#markup' => $item['weight']
        );
      }
    }
    return $ret;
  }

}

/**
 * Implements hook_views_api().
 */
function probabilistic_weight_views_api() {

  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'probabilistic_weight') . '/views',
  );

}
